name: Manually deploy your code

on:
  workflow_dispatch:
    inputs:
        environment:
          description: 'Define env name'     
          required: false
          default: 'prod'

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
        with:
          api_key: ${{secrets.HEROKU_BACKEND_API_KEY}}
          email: ${{secrets.HEROKU_BACKEND_EMAIL}}
          app_name: ${{secrets.HEROKU_BACKEND_APP_NAME}}
          heroku_branch: "main"
          subfolder: "server"
  
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
      - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
        with:
          api_key: ${{secrets.HEROKU_FRONTEND_API_KEY}}
          email: ${{secrets.HEROKU_FRONTEND_EMAIL}}
          app_name: ${{secrets.HEROKU_FRONTEND_APP_NAME}}
          heroku_branch: "main"
          subfolder: "client"